import { KpiInputType } from '@prisma/client';

type CatalogSeed = {
  key: string;
  parentKey?: string | null;
  titleUz: string;
  titleRu: string;
  descriptionUz?: string;
  descriptionRu?: string;
  inputType: KpiInputType;
  weight?: number;
  sortOrder: number;
  proofRequired?: boolean;
  frequency?: 'DAILY' | 'WEEKLY' | 'MONTHLY';
};

/** Tayyor manager KPI daraxti — yaratilmaydi, faqat seed */
export const KPI_CATALOG_SEED: CatalogSeed[] = [
  // —— Root columns (jadval) ——
  {
    key: 'clinic_inspection',
    titleUz: 'Klinika koʻrigi',
    titleRu: 'Осмотр клиники',
    inputType: 'GROUP',
    weight: 15,
    sortOrder: 1,
    proofRequired: true,
    frequency: 'DAILY',
  },
  {
    key: 'reception',
    titleUz: 'Retsepshn',
    titleRu: 'Рецепшен',
    inputType: 'GROUP',
    weight: 10,
    sortOrder: 2,
    proofRequired: true,
    frequency: 'DAILY',
  },
  {
    key: 'calls_new',
    titleUz: 'Yangi bemorlar qoʻngʻirogʻi',
    titleRu: 'Обзвон новых',
    descriptionUz: 'Qoʻngʻiroqlar / yozilganlar',
    descriptionRu: 'Звонки / записанные',
    inputType: 'RATIO',
    weight: 12,
    sortOrder: 3,
    proofRequired: true,
    frequency: 'DAILY',
  },
  {
    key: 'calls_repeat',
    titleUz: 'Takroriy qoʻngʻiroqlar',
    titleRu: 'Обзвон повторных',
    inputType: 'RATIO',
    weight: 8,
    sortOrder: 4,
    proofRequired: true,
    frequency: 'DAILY',
  },
  {
    key: 'calls_missed',
    titleUz: 'Oʻtkazib yuborilgan qoʻngʻiroqlar',
    titleRu: 'Пропущенные звонки',
    inputType: 'RATIO',
    weight: 8,
    sortOrder: 5,
    proofRequired: true,
    frequency: 'DAILY',
  },
  {
    key: 'reviews',
    titleUz: 'Bemor sharhlari',
    titleRu: 'Отзывы пациентов',
    inputType: 'NUMBER',
    weight: 8,
    sortOrder: 6,
    proofRequired: true,
    frequency: 'DAILY',
  },
  {
    key: 'uniform',
    titleUz: 'Xodimlar formasi',
    titleRu: 'Униформа сотрудников',
    inputType: 'GROUP',
    weight: 5,
    sortOrder: 7,
    proofRequired: true,
    frequency: 'DAILY',
  },
  {
    key: 'warehouse',
    titleUz: 'Ombor tahlili',
    titleRu: 'Склад анализ',
    inputType: 'CHECKBOX',
    weight: 5,
    sortOrder: 8,
    proofRequired: true,
    frequency: 'WEEKLY',
  },
  {
    key: 'seo',
    titleUz: 'SEO sayt',
    titleRu: 'SEO сайт',
    inputType: 'NOTE_CHECK',
    weight: 6,
    sortOrder: 9,
    proofRequired: true,
    frequency: 'WEEKLY',
  },
  {
    key: 'instagram',
    titleUz: 'Instagram',
    titleRu: 'Instagram',
    inputType: 'NOTE_CHECK',
    weight: 6,
    sortOrder: 10,
    proofRequired: true,
    frequency: 'WEEKLY',
  },
  {
    key: 'telegram_youtube',
    titleUz: 'Telegram / YouTube',
    titleRu: 'Телеграм/YouTube',
    inputType: 'NOTE_CHECK',
    weight: 5,
    sortOrder: 11,
    proofRequired: true,
    frequency: 'WEEKLY',
  },
  {
    key: 'ads_tv',
    titleUz: 'TV / radio reklama',
    titleRu: 'Реклама ТВ/радио',
    inputType: 'CHECKBOX',
    weight: 4,
    sortOrder: 12,
    proofRequired: true,
    frequency: 'MONTHLY',
  },
  {
    key: 'flyers',
    titleUz: 'Tarqatma material',
    titleRu: 'Раздаточный материал',
    inputType: 'CHECKBOX',
    weight: 3,
    sortOrder: 13,
    proofRequired: true,
    frequency: 'MONTHLY',
  },
  {
    key: 'doctor_patients',
    titleUz: 'Shifokordan kelgan bemorlar',
    titleRu: 'Пациенты от врачей',
    inputType: 'NUMBER',
    weight: 5,
    sortOrder: 14,
    proofRequired: false,
    frequency: 'DAILY',
  },

  // —— Klinika: 1-daraja (rasm 2) ——
  {
    key: 'clinic.cleanliness',
    parentKey: 'clinic_inspection',
    titleUz: 'Xonalar tozaligi',
    titleRu: 'Чистота помещений',
    descriptionUz: 'Pollar, devorlar, mebel, sanuzel',
    descriptionRu: 'Полы, стены, мебель, санузлы',
    inputType: 'GROUP',
    sortOrder: 1,
    proofRequired: true,
    frequency: 'DAILY',
  },
  {
    key: 'clinic.supplies',
    parentKey: 'clinic_inspection',
    titleUz: 'Zarur buyumlar',
    titleRu: 'Наличие необходимых вещей',
    descriptionUz: 'Qogʻoz, sovun, sochiq, dezinfektor',
    descriptionRu: 'Бумага, мыло, полотенца, дезинфекторы',
    inputType: 'CHECKBOX',
    sortOrder: 2,
    proofRequired: true,
  },
  {
    key: 'clinic.odor',
    parentKey: 'clinic_inspection',
    titleUz: 'Hid',
    titleRu: 'Запах',
    descriptionUz: 'Begona hid yoʻq, fresher bor',
    descriptionRu: 'Нет постороннего запаха, есть освежитель',
    inputType: 'CHECKBOX',
    sortOrder: 3,
    proofRequired: true,
  },
  {
    key: 'clinic.waste',
    parentKey: 'clinic_inspection',
    titleUz: 'Chiqindi qutilari',
    titleRu: 'Мусорные ведра',
    descriptionUz: 'Oʻz vaqtida utilizatsiya, sortirovka',
    descriptionRu: 'Своевременная утилизация, сортировка',
    inputType: 'CHECKBOX',
    sortOrder: 4,
    proofRequired: true,
  },
  {
    key: 'clinic.syringe',
    parentKey: 'clinic_inspection',
    titleUz: 'Shprits utilizatsiyasi',
    titleRu: 'Утилизация шприцов',
    descriptionUz: 'Konteynerlarni tekshirish',
    descriptionRu: 'Проверка контейнеров',
    inputType: 'CHECKBOX',
    sortOrder: 5,
    proofRequired: true,
  },
  {
    key: 'clinic.tv',
    parentKey: 'clinic_inspection',
    titleUz: 'TV reklama',
    titleRu: 'Реклама на ТВ',
    descriptionUz: 'Yoqilgan va ishlayapti',
    descriptionRu: 'Включена и работает',
    inputType: 'CHECKBOX',
    sortOrder: 6,
    proofRequired: true,
  },
  {
    key: 'clinic.music',
    parentKey: 'clinic_inspection',
    titleUz: 'Yoʻlakdagi musiqa',
    titleRu: 'Музыка в коридоре',
    descriptionUz: 'Yoqilgan, qulay ovoz',
    descriptionRu: 'Включена, комфортный уровень громкости',
    inputType: 'CHECKBOX',
    sortOrder: 7,
    proofRequired: true,
  },
  {
    key: 'clinic.ac',
    parentKey: 'clinic_inspection',
    titleUz: 'Konditsioner',
    titleRu: 'Кондиционер',
    descriptionUz: 'Zarurat boʻyicha yoqilgan/oʻchirilgan',
    descriptionRu: 'Включен/выключен по необходимости',
    inputType: 'CHECKBOX',
    sortOrder: 8,
    proofRequired: true,
  },
  {
    key: 'clinic.flowers',
    parentKey: 'clinic_inspection',
    titleUz: 'Gullar',
    titleRu: 'Цветы',
    descriptionUz: 'Sugʻorilgan, parvarishlangan',
    descriptionRu: 'Политы, ухожены',
    inputType: 'CHECKBOX',
    sortOrder: 9,
    proofRequired: true,
  },

  // —— Tozalik ichida (rasm 3) ——
  {
    key: 'clinic.cleanliness.floors',
    parentKey: 'clinic.cleanliness',
    titleUz: 'Pollar',
    titleRu: 'Полы',
    descriptionUz: 'Yuvilgan, chang va axlat yoʻq',
    descriptionRu: 'Вымыты, без пыли и мусора',
    inputType: 'GROUP',
    sortOrder: 1,
    proofRequired: true,
    frequency: 'DAILY',
  },
  {
    key: 'clinic.cleanliness.walls',
    parentKey: 'clinic.cleanliness',
    titleUz: 'Devor va mebel',
    titleRu: 'Стены и мебель',
    descriptionUz: 'Dogʻsiz, ozoda',
    descriptionRu: 'Без пятен, аккуратный вид',
    inputType: 'CHECKBOX',
    sortOrder: 2,
    proofRequired: true,
    frequency: 'DAILY',
  },
  {
    key: 'clinic.cleanliness.bathrooms',
    parentKey: 'clinic.cleanliness',
    titleUz: 'Sanuzellar',
    titleRu: 'Санузлы',
    descriptionUz: 'Toza, sovun va qogʻoz bor',
    descriptionRu: 'Чистые, наличие мыла, бумаги',
    inputType: 'CHECKBOX',
    sortOrder: 3,
    proofRequired: true,
    frequency: 'DAILY',
  },
  {
    key: 'clinic.cleanliness.windows',
    parentKey: 'clinic.cleanliness',
    titleUz: 'Deraza va eshiklar',
    titleRu: 'Окна и двери',
    descriptionUz: 'Shaffof, iz yoʻq',
    descriptionRu: 'Прозрачные, без разводов',
    inputType: 'CHECKBOX',
    sortOrder: 4,
    proofRequired: true,
    frequency: 'DAILY',
  },
  {
    key: 'clinic.cleanliness.hall',
    parentKey: 'clinic.cleanliness',
    titleUz: 'Yoʻlak va zal',
    titleRu: 'Коридоры и холл',
    descriptionUz: 'Axlat yoʻq, sirtlar toza',
    descriptionRu: 'Нет мусора, чистые поверхности',
    inputType: 'CHECKBOX',
    sortOrder: 5,
    proofRequired: true,
    frequency: 'DAILY',
  },

  // —— Pollar (rasm 4) ——
  {
    key: 'clinic.cleanliness.floors.wash',
    parentKey: 'clinic.cleanliness.floors',
    titleUz: 'Pollarni yuvish',
    titleRu: 'Мытьё полов',
    descriptionUz: 'Pollar yuvilgan, chang va kir yoʻq',
    descriptionRu: 'Полы вымыты, нет пыли и грязи',
    inputType: 'CHECKBOX',
    sortOrder: 1,
    proofRequired: true,
    frequency: 'DAILY',
  },
  {
    key: 'clinic.cleanliness.floors.trash',
    parentKey: 'clinic.cleanliness.floors',
    titleUz: 'Axlat yoʻqligi',
    titleRu: 'Отсутствие мусора',
    descriptionUz: 'Qogʻoz, quti, izlar yoʻq',
    descriptionRu: 'Нет бумажек, упаковок, следов',
    inputType: 'CHECKBOX',
    sortOrder: 2,
    proofRequired: true,
    frequency: 'DAILY',
  },
  {
    key: 'clinic.cleanliness.floors.dry',
    parentKey: 'clinic.cleanliness.floors',
    titleUz: 'Quruqlik va xavfsizlik',
    titleRu: 'Сухость и безопасность',
    descriptionUz: 'Koʻlmak yoʻq, sirpanchiq emas',
    descriptionRu: 'Нет луж, пол не скользкий',
    inputType: 'CHECKBOX',
    sortOrder: 3,
    proofRequired: true,
    frequency: 'DAILY',
  },
  {
    key: 'clinic.cleanliness.floors.smell',
    parentKey: 'clinic.cleanliness.floors',
    titleUz: 'Tozalik hidi',
    titleRu: 'Запах чистоты',
    descriptionUz: 'Yoqimsiz hid yoʻq, yangilik',
    descriptionRu: 'Нет неприятного запаха, свежесть',
    inputType: 'CHECKBOX',
    sortOrder: 4,
    proofRequired: true,
  },

  // —— Reception ——
  {
    key: 'reception.qr',
    parentKey: 'reception',
    titleUz: 'QR-kod',
    titleRu: 'QR-код',
    descriptionUz: 'Sharh uchun ishlayapti',
    descriptionRu: 'Работает для отзывов',
    inputType: 'CHECKBOX',
    sortOrder: 1,
    proofRequired: true,
    frequency: 'DAILY',
  },
  {
    key: 'reception.candy',
    parentKey: 'reception',
    titleUz: 'Konfet idishi',
    titleRu: 'Конфетница',
    inputType: 'CHECKBOX',
    sortOrder: 2,
    proofRequired: true,
  },
  {
    key: 'reception.cooler',
    parentKey: 'reception',
    titleUz: 'Kuller va suv',
    titleRu: 'Кулер и вода',
    inputType: 'CHECKBOX',
    sortOrder: 3,
    proofRequired: true,
  },
  {
    key: 'reception.meds',
    parentKey: 'reception',
    titleUz: 'Dorivor vositalar',
    titleRu: 'Лекарственные средства',
    inputType: 'CHECKBOX',
    sortOrder: 4,
    proofRequired: true,
  },
  {
    key: 'reception.cosmetics',
    parentKey: 'reception',
    titleUz: 'Kosmetika',
    titleRu: 'Косметика',
    inputType: 'CHECKBOX',
    sortOrder: 5,
    proofRequired: true,
  },

  // —— Uniform ——
  {
    key: 'uniform.gown',
    parentKey: 'uniform',
    titleUz: 'Xalatlar tozaligi',
    titleRu: 'Чистота халатов',
    inputType: 'CHECKBOX',
    sortOrder: 1,
    proofRequired: true,
    frequency: 'DAILY',
  },
  {
    key: 'uniform.condition',
    parentKey: 'uniform',
    titleUz: 'Forma holati',
    titleRu: 'Состояние формы',
    inputType: 'CHECKBOX',
    sortOrder: 2,
    proofRequired: true,
  },
  {
    key: 'uniform.badge',
    parentKey: 'uniform',
    titleUz: 'Bedj',
    titleRu: 'Бейдж',
    inputType: 'CHECKBOX',
    sortOrder: 3,
    proofRequired: true,
  },
  {
    key: 'uniform.standard',
    parentKey: 'uniform',
    titleUz: 'Korporativ standart',
    titleRu: 'Корпоративный стандарт',
    inputType: 'CHECKBOX',
    sortOrder: 4,
    proofRequired: true,
  },
];
